version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
  build:
    commands:
      - echo Build started on `date`
      - docker build -t nodejs-eks-app .
      - docker tag nodejs-eks-app:latest $ECR_REPO_URL:latest
  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push $ECR_REPO_URL:latest
      - echo Writing image definition to imagedefinitions.json...
      - printf '[{"name":"nodejs","imageUri":"%s"}]' $ECR_REPO_URL:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
