version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 073651099432.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo Building Docker image...
      - docker build -t nodejs-eks-app ./nodejs-eks-app
      - docker tag nodejs-eks-app:latest 073651099432.dkr.ecr.ap-south-1.amazonaws.com/eks-repo:latest

  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push 073651099432.dkr.ecr.ap-south-1.amazonaws.com/eks-repo:latest
      - echo Writing imagedefinitions.json...
      - printf '[{"name":"nodejs","imageUri":"%s"}]' 073651099432.dkr.ecr.ap-south-1.amazonaws.com/eks-repo:latest > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
