version: 0.2

env:
  variables:
    ECR_REPO: "073651099432.dkr.ecr.ap-south-1.amazonaws.com/eks-repo"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $ECR_REPO
  build:
    commands:
      - echo Build started on `date`
      - docker build -t nodejs-eks-app .
      - docker tag nodejs-eks-app:latest $ECR_REPO:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $ECR_REPO:latest
      - echo Writing imagedefinitions.json...
      - printf '[{"name":"nodejs","imageUri":"%s"}]' $ECR_REPO:latest > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json

