version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 073651099432.dkr.ecr.ap-south-1.amazonaws.com/eks-repo
  build:
    commands:
      - echo Build started on `date`
      - docker build -t nodejs-eks-app .
      - docker tag nodejs-eks-app:latest 073651099432.dkr.ecr.ap-south-1.amazonaws.com/eks-repo
  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push 073651099432.dkr.ecr.ap-south-1.amazonaws.com/eks-repo:latest 
      - echo Writing image definition to imagedefinitions.json...
      - printf '[{"name":"nodejs","imageUri":"%s"}]' $ECR_REPO_URL:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
